# Generated by Django 5.1.7 on 2026-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalUserProfile",
            fields=[
                (
                    "roll_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("hostel_number", models.CharField(max_length=50)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
